import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import Header from "@/components/layouts/main/Header";
import Footer from "@/components/layouts/main/Footer";
import localFont from "next/font/local";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const yekanBakhFont = localFont({
    src: "./fonts/yekanBakh/woff2/YekanBakhFaNum-Regular.woff2",
    variable: "--font-yekan-bakh-num",
    display: "swap"
});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
        <body className={`${yekanBakhFont.className} antialiased`}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
